# A build system is required to convert your code into a distributable package.
[build-system]
requires = ["setuptools<=80.10.2"]
build-backend = "setuptools.build_meta"

[project]
name = "multipa"
version = "0.0.0"
description = "MultIPA is yet another automatic speech transcription model into phonetic IPA."
readme = "README.md"

# What version of python does your library work with?
requires-python = ">=3.10,<3.12"

# Metadata about your package in case you upload it to PYPI
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

# All the dependencies needed for running your module go here
dependencies = [
    "datasets[audio]==4.8.4",
    "epitran==1.24",
    "eng_to_ipa",
    "evaluate==0.4.3",
    "fsspec==2023.9.2",
    "ipatok",
    "kaldialign",
    "librosa>=0.11.0",
    "mecab-python3==1.0.8",
    "pandas",
    "phonecodes>=2.0.0",
    "panphon @ git+https://github.com/dmort27/panphon.git@6acd3833743a49e63941a0b740ee69eae1dafc1c",
    "pyarrow",
    "pydub==0.25.1",
    "romkan==0.2.1",
    "torch==2.12.0",
    "torchcodec>=0.14.0",
    "soundfile",
    "transformers[torch]==4.43.4",
    "unidic==1.1.0",
]

[project.optional-dependencies]
# Extra dependencies only needed for running tests go here
test = [
    "pytest",
    ]

# Dependencies that are useful only to developers, like an autoformatter and support for visualizations in jupyter notebooks go here
dev = [
    "allosaurus",
    "epitran",
    "jinja2",
    "huggingface_hub",
    "matplotlib",
    "phonemizer",
    "ruff>=0.14.1",
    "seaborn",
    "scipy",
    "tqdm"
]

# Useful dependencies for GPU usage monitoring
gpu = [
    "nvidia-ml-py",
]

# If your project contains scripts you'd like to be available command line, you can define them here.
# The value must be of the form "<package_name>:<module_name>.<function>"
[project.scripts]
multipa-preprocess = "multipa:preprocess.main_cli"
multipa-train = "multipa:main.main_cli"
multipa-evaluate = "multipa:evaluation.main_cli"

[tool.setuptools]
include-package-data = true


[tool.ruff]
#GitHub editor is 127 chars wide
line-length = 127
# Don't care about Jupyter notebooks for checks
include=["*.py", "**/pyproject.toml"]
exclude=["scripts", "data", "analysis"]

[tool.ruff.lint]
select=["E","F"]
# Allow using lambda functions because they're useful with HuggingFace datasets library
ignore=["E731"]
